# Generated by Django 4.2.1 on 2023-11-15 14:49

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verifyUser', models.BooleanField(default=False)),
                ('Description', models.TextField(blank=True, null=True)),
                ('colorDescription', colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=18, null=True, samples=None)),
                ('photoProfile', models.CharField(blank=True, null=True)),
                ('BackgroundProfile', models.CharField(blank=True, null=True)),
                ('BackgroundBlur', models.IntegerField(blank=True, default=8, null=True)),
                ('gradientActive', models.BooleanField(default=True)),
                ('gradientOne', colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=18, null=True, samples=None)),
                ('gradientTwo', colorfield.fields.ColorField(blank=True, default='#4dffff', image_field=None, max_length=18, null=True, samples=None)),
                ('gradientoption', models.CharField(blank=True, choices=[('to top', 'Top'), ('to right top', 'Right top'), ('to right', 'Right'), ('to right bottom', 'Right bottom'), ('to bottom', 'Bottom'), ('to left bottom', 'Left bottom'), ('to left', 'Left'), ('to left top', 'Left top')], default='to top', max_length=30, null=True)),
                ('tiktokURL', models.CharField(blank=True, max_length=200, null=True)),
                ('instagramURL', models.CharField(blank=True, max_length=200, null=True)),
                ('youtubeURL', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedinURL', models.CharField(blank=True, max_length=200, null=True)),
                ('twitterURL', models.CharField(blank=True, max_length=200, null=True)),
                ('FacebookURL', models.CharField(blank=True, max_length=200, null=True)),
                ('GithubURL', models.CharField(blank=True, max_length=200, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=30, null=True)),
                ('LastName', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ItemPhotos/')),
                ('showPhoto', models.BooleanField(default=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('backgroundbox', colorfield.fields.ColorField(blank=True, default='#7a7a7a', image_field=None, max_length=18, null=True, samples=None)),
                ('backgoundActive', models.BooleanField(default=True)),
                ('gradientOne', colorfield.fields.ColorField(blank=True, default='#5558da', image_field=None, max_length=18, null=True, samples=None)),
                ('gradientTwo', colorfield.fields.ColorField(blank=True, default='#5fd1f9', image_field=None, max_length=18, null=True, samples=None)),
                ('gradientoption', models.CharField(blank=True, choices=[('to top', 'Top'), ('to right top', 'Right top'), ('to right', 'Right'), ('to right bottom', 'Right bottom'), ('to bottom', 'Bottom'), ('to left bottom', 'Left bottom'), ('to left', 'Left'), ('to left top', 'Left top')], default='to top', max_length=30, null=True)),
                ('BackgroundBlur', models.IntegerField(blank=True, default=8, null=True)),
                ('BackgroundBlurActive', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
            ],
        ),
    ]
