# Generated by Django 4.2.1 on 2023-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentPass', models.CharField(blank=True, max_length=100, null=True)),
                ('NewPass', models.CharField(blank=True, max_length=100, null=True)),
                ('ConNewPass', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktokURL', models.CharField(blank=True, max_length=200, null=True)),
                ('instagramURL', models.CharField(blank=True, max_length=200, null=True)),
                ('youtubeURL', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedinURL', models.CharField(blank=True, max_length=200, null=True)),
                ('twitterURL', models.CharField(blank=True, max_length=200, null=True)),
                ('FacebookURL', models.CharField(blank=True, max_length=200, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=30, null=True)),
                ('LastName', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=None)),
                ('username', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7, null=True)),
            ],
        ),
    ]
