# Generated by Django 4.2.1 on 2023-05-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Profile.username'),
            preserve_default=False,
        ),
    ]
