# Generated by Django 4.2.1 on 2023-05-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.AddField(
            model_name='username',
            name='slug',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
            preserve_default=False,
        ),
    ]
