# Generated by Django 4.2.1 on 2023-05-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_remove_profile_slug_username_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
        ),
    ]
