# Generated by Django 4.2.1 on 2023-05-30 12:59

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_rename_slug_username_allinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='colorUser',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='', upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
