# Generated by Django 4.2.1 on 2023-05-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_delete_changepassword_profile_connewpass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='BackgroundProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='BackgroundBlur',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='colorDescription',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gradientOne',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gradientTwo',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gradientoption',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photoProfile',
            field=models.ImageField(default='', upload_to=None),
            preserve_default=False,
        ),
    ]
