# Generated by Django 4.2.1 on 2023-05-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_alter_profile_backgroundprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gradientActive',
            field=models.BooleanField(default=False),
        ),
    ]
