# Generated by Django 4.2.1 on 2023-05-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_profile_verifyuser_alter_profile_gradientoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='colorDescription',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='colorUser',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
