# Generated by Django 4.2.1 on 2023-05-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0016_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='ItemPhotos/'),
            preserve_default=False,
        ),
    ]
