# Generated by Django 4.2.1 on 2023-06-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ConNewPass',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='CurrentPass',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='NewPass',
        ),
        migrations.AlterField(
            model_name='profile',
            name='BackgroundProfile',
            field=models.ImageField(null=True, upload_to='BackgroundProfiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photoProfile',
            field=models.ImageField(null=True, upload_to='PhotoProfiles/'),
        ),
    ]
