# Generated by Django 4.2.1 on 2023-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_remove_profile_connewpass_remove_profile_currentpass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='BackgroundProfile',
            field=models.ImageField(blank=True, null=True, upload_to='BackgroundProfiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photoProfile',
            field=models.ImageField(blank=True, null=True, upload_to='PhotoProfiles/'),
        ),
    ]
