# Generated by Django 4.2.1 on 2023-06-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0021_alter_profile_gradientone_alter_profile_gradienttwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gradientoption',
            field=models.CharField(blank=True, choices=[('to top', 'Top'), ('to right top', 'Right top'), ('to right', 'Right'), ('to right bottom', 'Right bottom'), ('to bottom', 'Bottom'), ('to left bottom', 'Left bottom'), ('to left', 'Left'), ('to left top', 'Left top')], default='to top', max_length=30, null=True),
        ),
    ]
