# Generated by Django 4.2.1 on 2023-06-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0025_alter_profile_photoprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='colorUser',
        ),
    ]
