# Generated by Django 4.2.1 on 2023-06-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0027_alter_profile_photoprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='BackgroundBlur',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='backgroundbox',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gradientOne',
            field=models.CharField(blank=True, default='#5558da', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gradientTwo',
            field=models.CharField(blank=True, default='#5fd1f9', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gradientoption',
            field=models.CharField(blank=True, choices=[('to top', 'Top'), ('to right top', 'Right top'), ('to right', 'Right'), ('to right bottom', 'Right bottom'), ('to bottom', 'Bottom'), ('to left bottom', 'Left bottom'), ('to left', 'Left'), ('to left top', 'Left top')], default='to top', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='showPhoto',
            field=models.BooleanField(default=True),
        ),
    ]
