# Generated by Django 4.2.1 on 2023-06-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0028_item_backgroundblur_item_backgroundbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='BackgroundBlurActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='BackgroundBlur',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
