# Generated by Django 4.2.1 on 2023-06-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0029_item_backgroundbluractive_alter_item_backgroundblur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ItemPhotos/'),
        ),
    ]
