# Generated by Django 4.2.1 on 2023-06-17 11:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0030_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gradientOne',
            field=colorfield.fields.ColorField(default='#5558da', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='gradientTwo',
            field=colorfield.fields.ColorField(default='#5fd1f9', image_field=None, max_length=18, samples=None),
        ),
    ]
