# Generated by Django 4.2.1 on 2023-06-17 11:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0031_alter_item_gradientone_alter_item_gradienttwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gradientOne',
            field=colorfield.fields.ColorField(blank=True, default='#5558da', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='gradientTwo',
            field=colorfield.fields.ColorField(blank=True, default='#5fd1f9', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
