# Generated by Django 4.2.1 on 2023-06-17 19:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0034_alter_item_backgroundbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='backgroundbox',
            field=colorfield.fields.ColorField(blank=True, default='#ff1f1f', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
