# Generated by Django 4.2.1 on 2023-06-18 15:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0035_alter_item_backgroundbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='colorDescription',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gradientOne',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gradientTwo',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
