# Generated by Django 4.2.1 on 2023-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0036_alter_profile_colordescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='backgoundActive',
            field=models.BooleanField(default=True),
        ),
    ]
