# Generated by Django 4.2.1 on 2023-06-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0037_item_backgoundactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='GithubURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
