# Generated by Django 4.2.1 on 2023-06-21 09:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0038_profile_githuburl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gradientOne',
            field=colorfield.fields.ColorField(blank=True, default='#ffffffFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gradientTwo',
            field=colorfield.fields.ColorField(blank=True, default='#ffffffff', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
