# Generated by Django 4.2.1 on 2023-06-21 15:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0041_alter_profile_gradientone_alter_profile_gradienttwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='backgroundbox',
            field=colorfield.fields.ColorField(blank=True, default='#7a7a7a', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
