# Generated by Django 4.2.1 on 2023-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0043_alter_profile_backgroundprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photoProfile',
            field=models.ImageField(blank=True, default='/asstes/images/806c33e6481b79ba7ec27073f24cb781.jpg', null=True, upload_to='PhotoProfiles/'),
        ),
    ]
