# Generated by Django 4.2.1 on 2023-10-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0044_alter_profile_photoprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photoProfile',
            field=models.ImageField(blank=True, null=True, upload_to='PhotoProfiles/'),
        ),
    ]
